name: PyUpdater Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [3.7, 3.8, 3.9]
        os: [windows-2022, ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox<4
      - name: Install self
        run: pip install -e .
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - uses: codecov/codecov-action@v4
